/*!
 * Dicut PS client — shared across Central Creative Tools.
 * Canonical source: dicut-bridge/client/dicut-ps.js
 * Contract: docs/contracts/DICUT_PS.md — copies in the tool repositories must
 * stay byte-identical to this file.
 *
 * Talks to the local Dicut PS Bridge (dicut_bridge.py) which drives the
 * Photoshop "Remove Background" command on Windows and macOS alike.
 * No dependencies, no build step: load it with a plain <script> tag.
 *
 * The install dialog hands out a one-file setup script with the whole bridge
 * embedded, so a first-time user never has to find or copy the source folder.
 * BRIDGE_SOURCE_B64 below is generated — after editing dicut_bridge.py run
 * `python tools/sync_client.py` to re-embed it and refresh every copy.
 */
(function () {
  'use strict';
  if (window.DicutPS) return;

  var VERSION = '1.1.6';
  // The bridge lives on the user's machine and is not updated by a site deploy,
  // so the client has to notice an old one and send them back to the installer.
  var REQUIRED_BRIDGE = '1.1.5';
  var ENDPOINT = 'http://127.0.0.1:8799';
  // document.currentScript is only readable while the script is executing, and
  // the stylesheet sits next to this file whatever path a tool serves it from.
  var SCRIPT_URL = (document.currentScript && document.currentScript.src) || '';
  var PROBE_TIMEOUT_MS = 2500;
  var CUT_TIMEOUT_MS = 240000;   // Photoshop's first launch can take minutes
  var PROBE_TTL_OK_MS = 15000;
  var PROBE_TTL_FAIL_MS = 3000;

  /* BRIDGE_SOURCE_B64_START */
  var BRIDGE_SOURCE_B64 = 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMw0KIyAtKi0gY29kaW5nOiB1dGYtOCAtKi0NCiIiIkRpY3V0IFBTIEJyaWRnZSAtIGxvY2FsIEhUVFAgc2VydmljZSB0aGF0IHJ1bnMgUGhvdG9zaG9wICJSZW1vdmUgQmFja2dyb3VuZCIuDQoNClRoZSBDZW50cmFsIENyZWF0aXZlIFRvb2xzIHdlYiBhcHBzIGNhbm5vdCB0YWxrIHRvIGEgbG9jYWxseSBpbnN0YWxsZWQNClBob3Rvc2hvcCwgc28gdGhleSBQT1NUIGFuIGltYWdlIGhlcmUgYW5kIGdldCBhIHRyYW5zcGFyZW50IFBORyBiYWNrLg0KVGhlIHNhbWUgc2VydmljZSBydW5zIG9uIFdpbmRvd3MgKENPTSkgYW5kIG1hY09TIChBcHBsZSBldmVudHMpLCB3aGljaCBpcyB3aGF0DQpsZXRzIG9uZSBidXR0b24gd29yayBvbiBib3RoIHBsYXRmb3Jtcy4NCg0KUnVuOiAgICAgICAgcHl0aG9uIGRpY3V0X2JyaWRnZS5weQ0KT3B0aW9uczogICAgLS1wb3J0IDg3OTkgIC0taG9zdCAxMjcuMC4wLjEgIC0tdGltZW91dCAxODAgIC0ta2VlcC13b3JrDQpIZWFsdGg6ICAgICBjdXJsIGh0dHA6Ly8xMjcuMC4wLjE6ODc5OS9oZWFsdGgNClNlbGYgdGVzdDogIHB5dGhvbiBkaWN1dF9icmlkZ2UucHkgLS1zZWxmdGVzdCBwYXRoL3RvL2ltYWdlLmpwZw0KDQpPbmx5IHRoZSBsb29wYmFjayBpbnRlcmZhY2UgaXMgYm91bmQgYW5kIG9ubHkgYWxsb3ctbGlzdGVkIGJyb3dzZXIgb3JpZ2lucyBhcmUNCmFjY2VwdGVkLCBzbyBhIHJhbmRvbSB3ZWIgcGFnZSBjYW5ub3QgZHJpdmUgdGhlIGxvY2FsIFBob3Rvc2hvcC4NCiIiIg0KDQppbXBvcnQgYXJncGFyc2UNCmltcG9ydCBiYXNlNjQNCmltcG9ydCBqc29uDQppbXBvcnQgb3MNCmltcG9ydCBwbGF0Zm9ybQ0KaW1wb3J0IHJlDQppbXBvcnQgc2h1dGlsDQppbXBvcnQgc3VicHJvY2Vzcw0KaW1wb3J0IHN5cw0KaW1wb3J0IHRlbXBmaWxlDQppbXBvcnQgdGhyZWFkaW5nDQppbXBvcnQgdGltZQ0KaW1wb3J0IHV1aWQNCmZyb20gaHR0cC5zZXJ2ZXIgaW1wb3J0IEJhc2VIVFRQUmVxdWVzdEhhbmRsZXIsIFRocmVhZGluZ0hUVFBTZXJ2ZXINCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aA0KDQpWRVJTSU9OID0gIjEuMS41IgpERUZBVUxUX1BPUlQgPSA4Nzk5DQpERUZBVUxUX0hPU1QgPSAiMTI3LjAuMC4xIg0KREVGQVVMVF9USU1FT1VUID0gMTgwDQpNQVhfQk9EWV9CWVRFUyA9IDQ4ICogMTAyNCAqIDEwMjQNCg0KSVNfV0lORE9XUyA9IHN5cy5wbGF0Zm9ybS5zdGFydHN3aXRoKCJ3aW4iKQ0KSVNfTUFDID0gc3lzLnBsYXRmb3JtID09ICJkYXJ3aW4iDQoNCiMgUHJvZHVjdGlvbiBvcmlnaW5zIG9mIHRoZSBhY3RpdmUgdG9vbHMgdGhhdCBvd24gYSBEaWN1dCBQUyBidXR0b24uIFByZXZpZXcKIyBkZXBsb3ltZW50cyBsaXZlIG9uIHN1YmRvbWFpbnMgb2YgdGhlIHNhbWUgUGFnZXMgcHJvamVjdHMsIHNvIHRob3NlIGFyZQ0KIyBtYXRjaGVkIGJ5IHN1ZmZpeC4gRXh0cmEgb3JpZ2lucyBjYW4gYmUgYWRkZWQgd2l0aCBESUNVVF9CUklER0VfT1JJR0lOUy4NCkFMTE9XRURfT1JJR0lOUyA9IHsNCiAgICAiaHR0cHM6Ly9jZW50cmFsLWltYWdlLWRvd25sb2FkZXIucGFnZXMuZGV2IiwNCiAgICAiaHR0cHM6Ly9jZW50cmFsLXN0cmlwLWJhbm5lci5wYWdlcy5kZXYiLA0KICAgICJodHRwczovL2NlbnRyYWwtb3ZlcmxheS1nZW5lcmF0b3IucGFnZXMuZGV2IiwNCiAgICAiaHR0cHM6Ly9jZW50cmFsLWZpcnN0LWltYWdlLmNoYWlyaXQtYmlyZC53b3JrZXJzLmRldiIsCiAgICAiaHR0cHM6Ly9jZW50cmFsLWd3cC1lZGl0b3IucGFnZXMuZGV2IiwKfQ0KQUxMT1dFRF9PUklHSU5fU1VGRklYRVMgPSAoDQogICAgIi5jZW50cmFsLWltYWdlLWRvd25sb2FkZXIucGFnZXMuZGV2IiwNCiAgICAiLmNlbnRyYWwtc3RyaXAtYmFubmVyLnBhZ2VzLmRldiIsDQogICAgIi5jZW50cmFsLW92ZXJsYXktZ2VuZXJhdG9yLnBhZ2VzLmRldiIsCiAgICAiLmNlbnRyYWwtZ3dwLWVkaXRvci5wYWdlcy5kZXYiLAopDQpMT0NBTF9PUklHSU5fUkUgPSByZS5jb21waWxlKHIiXmh0dHBzPzovLyhsb2NhbGhvc3R8MTI3XC4wXC4wXC4xfFxbOjoxXF0pKDpcZCspPyQiKQ0KDQpFWFRFTlNJT05fQllfTUlNRSA9IHsNCiAgICAiaW1hZ2UvcG5nIjogIi5wbmciLA0KICAgICJpbWFnZS9qcGVnIjogIi5qcGciLA0KICAgICJpbWFnZS9qcGciOiAiLmpwZyIsDQogICAgImltYWdlL3dlYnAiOiAiLndlYnAiLA0KICAgICJpbWFnZS90aWZmIjogIi50aWYiLA0KICAgICJpbWFnZS9ibXAiOiAiLmJtcCIsDQp9DQoNCkRBVEFfVVJMX1JFID0gcmUuY29tcGlsZShyIl5kYXRhOig/UDxtaW1lPltcdy4rLV0rL1tcdy4rLV0rKT87YmFzZTY0LCg/UDxwYXlsb2FkPi4rKSQiLCByZS5TKQ0KDQojIFBob3Rvc2hvcCBpcyBzaW5nbGUtaW5zdGFuY2U6IHR3byBvdmVybGFwcGluZyBEb0phdmFTY3JpcHQgY2FsbHMgZmlnaHQgb3Zlcg0KIyB0aGUgc2FtZSBhcHBsaWNhdGlvbiwgc28gZXZlcnkgY3V0IGlzIHNlcmlhbGlzZWQuDQpQSE9UT1NIT1BfTE9DSyA9IHRocmVhZGluZy5Mb2NrKCkNCg0KIyBUcmltbWluZyBpcyBvcHRpb25hbDogYSBjYWxsZXIgdGhhdCB3YW50cyBhIGJlZm9yZS9hZnRlciBjb21wYXJpc29uIG5lZWRzIHRoZQ0KIyByZXN1bHQgb24gdGhlIG9yaWdpbmFsIGNhbnZhcywgYmVjYXVzZSBhIHRyaW1tZWQgY3V0b3V0IG5vIGxvbmdlciBsaW5lcyB1cA0KIyB3aXRoIHRoZSBpbWFnZSBpdCBjYW1lIGZyb20uDQpKU1hfVEVNUExBVEUgPSAiIiJhcHAuZGlzcGxheURpYWxvZ3MgPSBEaWFsb2dNb2Rlcy5OTzsNCnZhciBfc3JjID0gbmV3IEZpbGUoIiUoc3JjKXMiKTsNCnZhciBfb3V0ID0gbmV3IEZpbGUoIiUob3V0KXMiKTsNCnZhciBkb2MgPSBhcHAub3Blbihfc3JjKTsNCnRyeSB7DQogICAgaWYgKGRvYy5sYXllcnNbMF0uaXNCYWNrZ3JvdW5kTGF5ZXIpIGRvYy5sYXllcnNbMF0uaXNCYWNrZ3JvdW5kTGF5ZXIgPSBmYWxzZTsNCiAgICBleGVjdXRlQWN0aW9uKHN0cmluZ0lEVG9UeXBlSUQoJ3JlbW92ZUJhY2tncm91bmQnKSwgdW5kZWZpbmVkLCBEaWFsb2dNb2Rlcy5OTyk7DQolKHRyaW0pcyAgICBkb2Muc2F2ZUFzKF9vdXQsIG5ldyBQTkdTYXZlT3B0aW9ucygpLCB0cnVlLCBFeHRlbnNpb24uTE9XRVJDQVNFKTsNCn0gZmluYWxseSB7DQogICAgZG9jLmNsb3NlKFNhdmVPcHRpb25zLkRPTk9UU0FWRUNIQU5HRVMpOw0KfQ0KIiIiDQpUUklNX0xJTkUgPSAiICAgIGRvYy50cmltKFRyaW1UeXBlLlRSQU5TUEFSRU5UKTtcbiINCg0KDQpMT0dfUEFUSCA9IFBhdGguaG9tZSgpIC8gIi5kaWN1dC1icmlkZ2UiIC8gImJyaWRnZS5sb2ciDQoNCg0KZGVmIGVtaXQobWVzc2FnZSk6DQogICAgIiIiUmVwb3J0IGEgbGluZSB3aXRob3V0IGFzc3VtaW5nIHRoZXJlIGlzIGEgY29uc29sZS4NCg0KICAgIHB5dGhvbncuZXhlIC0gd2hpY2ggdGhlIFdpbmRvd3MgaW5zdGFsbGVyIHVzZXMgc28gdGhlIGJyaWRnZSBoYXMgbm8gdmlzaWJsZQ0KICAgIHdpbmRvdyAtIGxlYXZlcyBzeXMuc3Rkb3V0IGFzIE5vbmUsIHNvIHdyaXRpbmcgdG8gaXQgcmFpc2VkIEF0dHJpYnV0ZUVycm9yDQogICAgYW5kIGtpbGxlZCB0aGUgc2VydmljZSBiZWZvcmUgaXQgZXZlciBib3VuZCB0aGUgcG9ydC4gQW55dGhpbmcgdGhhdCBjYW5ub3QNCiAgICByZWFjaCBhIHN0cmVhbSBnb2VzIHRvIGEgbG9nIGZpbGUgaW5zdGVhZCwgd2hpY2ggaXMgYWxzbyB3aGF0IG1ha2VzIGENCiAgICBoZWFkbGVzcyBmYWlsdXJlIGRpYWdub3NhYmxlIGF0IGFsbC4NCiAgICAiIiINCiAgICBsaW5lID0gIiVzICVzIiAlICh0aW1lLnN0cmZ0aW1lKCIlSDolTTolUyIpLCBtZXNzYWdlKQ0KICAgIHN0cmVhbSA9IHN5cy5zdGRvdXQNCiAgICBpZiBzdHJlYW0gaXMgbm90IE5vbmU6DQogICAgICAgIHRyeToNCiAgICAgICAgICAgIHN0cmVhbS53cml0ZShsaW5lICsgIlxuIikNCiAgICAgICAgICAgIHN0cmVhbS5mbHVzaCgpDQogICAgICAgICAgICByZXR1cm4NCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogICMgbm9xYTogQkxFMDAxIC0gYSBicm9rZW4gY29uc29sZSBtdXN0IG5vdCBzdG9wIHRoZSBzZXJ2aWNlDQogICAgICAgICAgICBwYXNzDQogICAgdHJ5Og0KICAgICAgICBMT0dfUEFUSC5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQ0KICAgICAgICB3aXRoIExPR19QQVRILm9wZW4oImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBoYW5kbGU6DQogICAgICAgICAgICBoYW5kbGUud3JpdGUobGluZSArICJcbiIpDQogICAgZXhjZXB0IE9TRXJyb3I6DQogICAgICAgIHBhc3MNCg0KDQpjbGFzcyBEaWN1dEVycm9yKFJ1bnRpbWVFcnJvcik6DQogICAgIiIiQSBmYWlsdXJlIHRoZSBicm93c2VyIGlzIGV4cGVjdGVkIHRvIHNob3cgdG8gdGhlIHVzZXIgYXMtaXMuIiIiDQoNCg0KZGVmIGpzeF9wYXRoKHZhbHVlKToNCiAgICAiIiJFc2NhcGUgYSBmaWxlc3lzdGVtIHBhdGggZm9yIGVtYmVkZGluZyBpbiBhIEpTWCBzdHJpbmcgbGl0ZXJhbC4iIiINCiAgICByZXR1cm4gc3RyKHZhbHVlKS5yZXBsYWNlKCJcXCIsICJcXFxcIikucmVwbGFjZSgnIicsICdcXCInKQ0KDQoNCmRlZiBvcmlnaW5fYWxsb3dlZChvcmlnaW4pOg0KICAgIGlmIG5vdCBvcmlnaW46DQogICAgICAgIHJldHVybiBUcnVlICAjIGN1cmwgLyBzZWxmIHRlc3Q6IG5vIGJyb3dzZXIgb3JpZ2luIHRvIGNoZWNrDQogICAgaWYgb3JpZ2luIGluIEFMTE9XRURfT1JJR0lOUyBvciBMT0NBTF9PUklHSU5fUkUubWF0Y2gob3JpZ2luKToNCiAgICAgICAgcmV0dXJuIFRydWUNCiAgICByZXR1cm4gYW55KG9yaWdpbi5lbmRzd2l0aChzdWZmaXgpIGZvciBzdWZmaXggaW4gQUxMT1dFRF9PUklHSU5fU1VGRklYRVMpDQoNCg0KZGVmIGxvYWRfZXh0cmFfb3JpZ2lucygpOg0KICAgIHJhdyA9IG9zLmVudmlyb24uZ2V0KCJESUNVVF9CUklER0VfT1JJR0lOUyIsICIiKQ0KICAgIGZvciBpdGVtIGluIHJhdy5yZXBsYWNlKCIsIiwgIiAiKS5zcGxpdCgpOg0KICAgICAgICBBTExPV0VEX09SSUdJTlMuYWRkKGl0ZW0ucnN0cmlwKCIvIikpDQoNCg0KIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIyBQaG90b3Nob3AgZGlzY292ZXJ5DQojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoNCmRlZiBmaW5kX3Bob3Rvc2hvcF9tYWMoKToNCiAgICBjYW5kaWRhdGVzID0gW10NCiAgICBhcHBzID0gUGF0aCgiL0FwcGxpY2F0aW9ucyIpDQogICAgaWYgYXBwcy5pc19kaXIoKToNCiAgICAgICAgZm9yIGVudHJ5IGluIHNvcnRlZChhcHBzLmdsb2IoIkFkb2JlIFBob3Rvc2hvcCoiKSk6DQogICAgICAgICAgICBpZiBlbnRyeS5zdWZmaXggPT0gIi5hcHAiOg0KICAgICAgICAgICAgICAgIGNhbmRpZGF0ZXMuYXBwZW5kKGVudHJ5KQ0KICAgICAgICAgICAgZWxpZiBlbnRyeS5pc19kaXIoKToNCiAgICAgICAgICAgICAgICBjYW5kaWRhdGVzLmV4dGVuZChzb3J0ZWQoZW50cnkuZ2xvYigiQWRvYmUgUGhvdG9zaG9wKi5hcHAiKSkpDQogICAgcmV0dXJuIGNhbmRpZGF0ZXNbLTFdIGlmIGNhbmRpZGF0ZXMgZWxzZSBOb25lDQoNCg0KZGVmIGZpbmRfcGhvdG9zaG9wX3dpbmRvd3MoKToNCiAgICAiIiJSZXR1cm4gdGhlIHJlZ2lzdGVyZWQgUGhvdG9zaG9wIGFwcGxpY2F0aW9uIG5hbWUsIG9yIE5vbmUuIiIiDQogICAgdHJ5Og0KICAgICAgICBpbXBvcnQgd2lucmVnDQogICAgZXhjZXB0IEltcG9ydEVycm9yOiAgIyBwcmFnbWE6IG5vIGNvdmVyIC0gV2luZG93cyBvbmx5DQogICAgICAgIHJldHVybiBOb25lDQogICAgZm9yIHJvb3QgaW4gKHdpbnJlZy5IS0VZX0NMQVNTRVNfUk9PVCwpOg0KICAgICAgICB0cnk6DQogICAgICAgICAgICB3aXRoIHdpbnJlZy5PcGVuS2V5KHJvb3QsIHIiUGhvdG9zaG9wLkFwcGxpY2F0aW9uXEN1clZlciIpIGFzIGtleToNCiAgICAgICAgICAgICAgICB2ZXJzaW9uID0gd2lucmVnLlF1ZXJ5VmFsdWVFeChrZXksICIiKVswXQ0KICAgICAgICAgICAgICAgIHJldHVybiBzdHIodmVyc2lvbikNCiAgICAgICAgZXhjZXB0IE9TRXJyb3I6DQogICAgICAgICAgICBjb250aW51ZQ0KICAgIHRyeToNCiAgICAgICAgd2l0aCB3aW5yZWcuT3BlbktleSh3aW5yZWcuSEtFWV9DTEFTU0VTX1JPT1QsICJQaG90b3Nob3AuQXBwbGljYXRpb24iKToNCiAgICAgICAgICAgIHJldHVybiAiUGhvdG9zaG9wLkFwcGxpY2F0aW9uIg0KICAgIGV4Y2VwdCBPU0Vycm9yOg0KICAgICAgICByZXR1cm4gTm9uZQ0KDQoNCmRlZiBwaG90b3Nob3Bfc3RhdHVzKCk6DQogICAgaWYgSVNfTUFDOg0KICAgICAgICBhcHAgPSBmaW5kX3Bob3Rvc2hvcF9tYWMoKQ0KICAgICAgICByZXR1cm4geyJmb3VuZCI6IGJvb2woYXBwKSwgIm5hbWUiOiBhcHAuc3RlbSBpZiBhcHAgZWxzZSAiIiwgInBhdGgiOiBzdHIoYXBwKSBpZiBhcHAgZWxzZSAiIn0NCiAgICBpZiBJU19XSU5ET1dTOg0KICAgICAgICBuYW1lID0gZmluZF9waG90b3Nob3Bfd2luZG93cygpDQogICAgICAgIHJldHVybiB7ImZvdW5kIjogYm9vbChuYW1lKSwgIm5hbWUiOiBuYW1lIG9yICIiLCAicGF0aCI6ICIifQ0KICAgIHJldHVybiB7ImZvdW5kIjogRmFsc2UsICJuYW1lIjogIiIsICJwYXRoIjogIiJ9DQoNCg0KIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIyBQaG90b3Nob3AgZXhlY3V0aW9uDQojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoNCmRlZiB3YWl0X2Zvcl9vdXRwdXQob3V0X2ZpbGUsIGFwcGVhcl90aW1lb3V0LCBzZXR0bGVfdGltZW91dD0xODAsIHBvbGw9MC4zKToNCiAgICAiIiJXYWl0IHVudGlsIHRoZSBQTkcgZXhpc3RzIGFuZCBoYXMgc3RvcHBlZCBncm93aW5nLg0KDQogICAgUGhvdG9zaG9wIGNyZWF0ZXMgdGhlIG91dHB1dCBmaWxlIGJlZm9yZSBpdCBoYXMgZmluaXNoZWQgd3JpdGluZyBpdCwgc28NCiAgICB0ZXN0aW5nIGBleGlzdHMoKWAgYWxvbmUgaGFuZHMgYmFjayBhIHplcm8tYnl0ZSBvciBoYWxmLXdyaXR0ZW4gUE5HLiBUaGF0IGlzDQogICAgd2hhdCBtYWRlIGEgbWFjT1MgYmF0Y2ggcmV0dXJuICJQaG90b3Nob3Ag4LiE4Li34LiZ4LmE4Lif4Lil4LmM4Lin4LmI4Liy4LiHIiBmb3IgZXZlcnkgaW1hZ2UgZXhjZXB0DQogICAgdGhlIG9uZSB0aGF0IGhhcHBlbmVkIHRvIHdpbiB0aGUgcmFjZS4NCiAgICAiIiINCiAgICBhcHBlYXJfZGVhZGxpbmUgPSB0aW1lLnRpbWUoKSArIGFwcGVhcl90aW1lb3V0DQogICAgd2hpbGUgdGltZS50aW1lKCkgPCBhcHBlYXJfZGVhZGxpbmUgYW5kIG5vdCBvdXRfZmlsZS5leGlzdHMoKToNCiAgICAgICAgdGltZS5zbGVlcChwb2xsKQ0KICAgIGlmIG5vdCBvdXRfZmlsZS5leGlzdHMoKToNCiAgICAgICAgcmV0dXJuIEZhbHNlDQoNCiAgICBzZXR0bGVfZGVhZGxpbmUgPSB0aW1lLnRpbWUoKSArIHNldHRsZV90aW1lb3V0DQogICAgbGFzdCwgc3RhYmxlID0gLTEsIDANCiAgICB3aGlsZSB0aW1lLnRpbWUoKSA8IHNldHRsZV9kZWFkbGluZToNCiAgICAgICAgdHJ5Og0KICAgICAgICAgICAgc2l6ZSA9IG91dF9maWxlLnN0YXQoKS5zdF9zaXplDQogICAgICAgIGV4Y2VwdCBPU0Vycm9yOg0KICAgICAgICAgICAgc2l6ZSA9IC0xDQogICAgICAgIGlmIHNpemUgPiAwIGFuZCBzaXplID09IGxhc3Q6DQogICAgICAgICAgICBzdGFibGUgKz0gMQ0KICAgICAgICAgICAgaWYgc3RhYmxlID49IDI6DQogICAgICAgICAgICAgICAgcmV0dXJuIFRydWUNCiAgICAgICAgZWxzZToNCiAgICAgICAgICAgIHN0YWJsZSA9IDANCiAgICAgICAgbGFzdCA9IHNpemUNCiAgICAgICAgdGltZS5zbGVlcChwb2xsKQ0KICAgIHJldHVybiBGYWxzZQ0KDQoNCmRlZiBydW5fcGhvdG9zaG9wX3dpbmRvd3Moc2NyaXB0LCBvdXRfZmlsZSwgdGltZW91dCk6CiAgICAiIiJEcml2ZSBQaG90b3Nob3AgdGhyb3VnaCBDT006IHB5d2luMzIgd2hlbiBwcmVzZW50LCBQb3dlclNoZWxsIG90aGVyd2lzZS4iIiIKICAgIGVycm9ycyA9IFtdCiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5dGhvbmNvbSAgIyB0eXBlOiBpZ25vcmUKICAgICAgICBpbXBvcnQgd2luMzJjb20uY2xpZW50ICAjIHR5cGU6IGlnbm9yZQoKICAgICAgICAjIFRocmVhZGluZ0hUVFBTZXJ2ZXIgZ2l2ZXMgZXZlcnkgcmVxdWVzdCBhIGZyZXNoIHdvcmtlciB0aHJlYWQuIENPTSBoYXMKICAgICAgICAjIHRvIGJlIGluaXRpYWxpc2VkIGluIHRoYXQgZXhhY3QgdGhyZWFkIGJlZm9yZSBweXdpbjMyIGNhbiB0YWxrIHRvIHRoZQogICAgICAgICMgYWxyZWFkeS1ydW5uaW5nIFBob3Rvc2hvcCBpbnN0YW5jZS4KICAgICAgICBweXRob25jb20uQ29Jbml0aWFsaXplKCkKICAgICAgICB0cnk6CiAgICAgICAgICAgIGxhdW5jaGVkID0gRmFsc2UKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgIyBBZG9iZSBQaG90b3Nob3AgaXMgYSBzaW5nbGV0b24sIGJ1dCBEaXNwYXRjaC9OZXctT2JqZWN0IGNhbgogICAgICAgICAgICAgICAgIyBzdGlsbCBhc2sgQ09NIHRvIGNyZWF0ZSBhIHNlY29uZCBhdXRvbWF0aW9uIHNlcnZlci4gV2l0aCBib3RoCiAgICAgICAgICAgICAgICAjIHRoZSBzdGFibGUgYW5kIEJldGEgYnVpbGRzIGluc3RhbGxlZCB0aGF0IGNyYXNoZXMgdGhlIGFjdGl2ZQogICAgICAgICAgICAgICAgIyBwcm9jZXNzIChSUEMgMHg4MDA3MDZCRSkuIFJldXNlIHRoZSBST1Qgb2JqZWN0IHdoZW5ldmVyIG9uZSBpcwogICAgICAgICAgICAgICAgIyBhbHJlYWR5IHJ1bm5pbmcgYW5kIG9ubHkgbGF1bmNoIHdoZW4gdGhlcmUgdHJ1bHkgaXMgbm9uZS4KICAgICAgICAgICAgICAgIGFwcCA9IHdpbjMyY29tLmNsaWVudC5HZXRBY3RpdmVPYmplY3QoIlBob3Rvc2hvcC5BcHBsaWNhdGlvbiIpCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246ICAjIG5vcWE6IEJMRTAwMSAtIGFic2VuY2UgZnJvbSB0aGUgUk9UIGlzIGV4cGVjdGVkCiAgICAgICAgICAgICAgICBhcHAgPSB3aW4zMmNvbS5jbGllbnQuRGlzcGF0Y2goIlBob3Rvc2hvcC5BcHBsaWNhdGlvbiIpCiAgICAgICAgICAgICAgICBsYXVuY2hlZCA9IFRydWUKCiAgICAgICAgICAgICMgRGlzcGF0Y2ggY2FuIHJldHVybiB3aGlsZSBQaG90b3Nob3AncyBob21lIHNjcmVlbiBpcyB2aXNpYmxlIGJ1dAogICAgICAgICAgICAjIGl0cyBzY3JpcHRpbmcgaG9zdCBpcyBzdGlsbCBmaW5pc2hpbmcgc3RhcnR1cC4gVG91Y2ggdHdvIGhhcm1sZXNzCiAgICAgICAgICAgICMgcHJvcGVydGllcyB1bnRpbCBDT00gaXMgcmVzcG9uc2l2ZSwgdGhlbiBnaXZlIGEgbmV3bHkgbGF1bmNoZWQKICAgICAgICAgICAgIyBob3N0IGEgc2hvcnQgc2V0dGxlIHdpbmRvdyBiZWZvcmUgc2VuZGluZyB0aGUgZmlyc3QgSlNYIHBheWxvYWQuCiAgICAgICAgICAgIHJlYWR5X2RlYWRsaW5lID0gdGltZS50aW1lKCkgKyBtaW4obWF4KHRpbWVvdXQsIDEpLCAzMCkKICAgICAgICAgICAgd2hpbGUgVHJ1ZToKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICBfID0gYXBwLlZlcnNpb24KICAgICAgICAgICAgICAgICAgICBfID0gYXBwLkRvY3VtZW50cy5Db3VudAogICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOiAgIyBub3FhOiBCTEUwMDEgLSB0cmFuc2llbnQgZHVyaW5nIGNvbGQgc3RhcnQKICAgICAgICAgICAgICAgICAgICBpZiB0aW1lLnRpbWUoKSA+PSByZWFkeV9kZWFkbGluZToKICAgICAgICAgICAgICAgICAgICAgICAgcmFpc2UKICAgICAgICAgICAgICAgICAgICB0aW1lLnNsZWVwKDAuNSkKICAgICAgICAgICAgaWYgbGF1bmNoZWQ6CiAgICAgICAgICAgICAgICB0aW1lLnNsZWVwKDIpCiAgICAgICAgICAgICMgRG9KYXZhU2NyaXB0IHdpdGggdGhlIHNvdXJjZSB0ZXh0IGlzIHRoZSBjYWxsIHBhdGggYWxyZWFkeSBwcm92ZW4gYnkKICAgICAgICAgICAgIyB0b29scy9kaWN1dC5weTsgdGhlIHBhdGhzIGFyZSBiYWtlZCBpbnRvIHRoZSBzY3JpcHQgc28gbm8gYXJndW1lbnRzCiAgICAgICAgICAgICMgaGF2ZSB0byBzdXJ2aXZlIHRoZSBDT00gYm91bmRhcnkuCiAgICAgICAgICAgIGFwcC5Eb0phdmFTY3JpcHQoc2NyaXB0LnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSkKICAgICAgICAgICAgaWYgd2FpdF9mb3Jfb3V0cHV0KG91dF9maWxlLCA1KToKICAgICAgICAgICAgICAgIHJldHVybiAiY29tIgogICAgICAgICAgICBlcnJvcnMuYXBwZW5kKCJweXdpbjMyIHJhbiB0aGUgc2NyaXB0IGJ1dCBwcm9kdWNlZCBubyB1c2FibGUgb3V0cHV0IGZpbGUiKQogICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgIGFwcCA9IE5vbmUKICAgICAgICAgICAgcHl0aG9uY29tLkNvVW5pbml0aWFsaXplKCkKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXJyb3I6ICAjIG5vcWE6IEJMRTAwMSAtIHJlcG9ydGVkIHRvIHRoZSB1c2VyIHZlcmJhdGltDQogICAgICAgIGVycm9ycy5hcHBlbmQoInB5d2luMzI6ICVzIiAlIGVycm9yKQ0KDQogICAgcG93ZXJzaGVsbCA9IHNodXRpbC53aGljaCgicG93ZXJzaGVsbCIpIG9yIHNodXRpbC53aGljaCgicHdzaCIpDQogICAgaWYgcG93ZXJzaGVsbDoNCiAgICAgICAgY29tbWFuZCA9ICgKICAgICAgICAgICAgIiRFcnJvckFjdGlvblByZWZlcmVuY2U9J1N0b3AnOyIKICAgICAgICAgICAgIiRsYXVuY2hlZD0kZmFsc2U7IgogICAgICAgICAgICAidHJ5eyRhcHA9W1J1bnRpbWUuSW50ZXJvcFNlcnZpY2VzLk1hcnNoYWxdOjpHZXRBY3RpdmVPYmplY3QoJ1Bob3Rvc2hvcC5BcHBsaWNhdGlvbicpfSIKICAgICAgICAgICAgImNhdGNoeyRhcHA9TmV3LU9iamVjdCAtQ29tT2JqZWN0IFBob3Rvc2hvcC5BcHBsaWNhdGlvbjskbGF1bmNoZWQ9JHRydWV9OyIKICAgICAgICAgICAgImlmKCRsYXVuY2hlZCl7JG51bGw9JGFwcC5WZXJzaW9uO1N0YXJ0LVNsZWVwIC1TZWNvbmRzIDJ9OyIKICAgICAgICAgICAgIiRhcHAuRG9KYXZhU2NyaXB0RmlsZSgnJXMnKSIgJSBzdHIoc2NyaXB0KS5yZXBsYWNlKCInIiwgIicnIikKICAgICAgICApCiAgICAgICAgdHJ5Og0KICAgICAgICAgICAgZG9uZSA9IHN1YnByb2Nlc3MucnVuKA0KICAgICAgICAgICAgICAgIFtwb3dlcnNoZWxsLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLUNvbW1hbmQiLCBjb21tYW5kXSwNCiAgICAgICAgICAgICAgICBjYXB0dXJlX291dHB1dD1UcnVlLCB0ZXh0PVRydWUsIHRpbWVvdXQ9dGltZW91dCwNCiAgICAgICAgICAgICkNCiAgICAgICAgICAgIGlmIHdhaXRfZm9yX291dHB1dChvdXRfZmlsZSwgNSk6DQogICAgICAgICAgICAgICAgcmV0dXJuICJwb3dlcnNoZWxsIg0KICAgICAgICAgICAgZXJyb3JzLmFwcGVuZCgicG93ZXJzaGVsbDogJXMiICUgKGRvbmUuc3RkZXJyIG9yIGRvbmUuc3Rkb3V0IG9yICJubyBvdXRwdXQgZmlsZSIpLnN0cmlwKCkpDQogICAgICAgIGV4Y2VwdCBzdWJwcm9jZXNzLlRpbWVvdXRFeHBpcmVkOg0KICAgICAgICAgICAgZXJyb3JzLmFwcGVuZCgicG93ZXJzaGVsbDogdGltZW91dCBhZnRlciAlc3MiICUgdGltZW91dCkNCiAgICAgICAgZXhjZXB0IE9TRXJyb3IgYXMgZXJyb3I6DQogICAgICAgICAgICBlcnJvcnMuYXBwZW5kKCJwb3dlcnNoZWxsOiAlcyIgJSBlcnJvcikNCiAgICBlbHNlOg0KICAgICAgICBlcnJvcnMuYXBwZW5kKCJwb3dlcnNoZWxsIG5vdCBmb3VuZCBvbiBQQVRIIikNCg0KICAgIHJhaXNlIERpY3V0RXJyb3IoIlBob3Rvc2hvcCDguYTguKHguYjguJXguK3guJrguKrguJnguK3guIcg4oCUICIgKyAiIHwgIi5qb2luKGVycm9ycykpDQoNCg0KZGVmIHJ1bl9waG90b3Nob3BfbWFjKHNjcmlwdCwgb3V0X2ZpbGUsIHRpbWVvdXQsIGFwcF9wYXRoKToNCiAgICBpZiBub3QgYXBwX3BhdGg6DQogICAgICAgIHJhaXNlIERpY3V0RXJyb3IoIuC5hOC4oeC5iOC4nuC4miBBZG9iZSBQaG90b3Nob3Ag4LmD4LiZIC9BcHBsaWNhdGlvbnMiKQ0KICAgIG5hbWUgPSBhcHBfcGF0aC5zdGVtDQogICAgZXJyb3JzID0gW10NCiAgICB0cnk6DQogICAgICAgIGRvbmUgPSBzdWJwcm9jZXNzLnJ1bigNCiAgICAgICAgICAgIFsNCiAgICAgICAgICAgICAgICAib3Nhc2NyaXB0IiwNCiAgICAgICAgICAgICAgICAiLWUiLCAndGVsbCBhcHBsaWNhdGlvbiAiJXMiIHRvIGFjdGl2YXRlJyAlIG5hbWUsDQogICAgICAgICAgICAgICAgIi1lIiwgJ3RlbGwgYXBwbGljYXRpb24gIiVzIiB0byBkbyBqYXZhc2NyaXB0IChQT1NJWCBmaWxlICIlcyIpJyAlIChuYW1lLCBzY3JpcHQpLA0KICAgICAgICAgICAgXSwNCiAgICAgICAgICAgIGNhcHR1cmVfb3V0cHV0PVRydWUsIHRleHQ9VHJ1ZSwgdGltZW91dD10aW1lb3V0LA0KICAgICAgICApDQogICAgICAgICMgQSBzaG9ydCBhcHBlYXIgd2luZG93OiBpZiBvc2FzY3JpcHQgcmVhbGx5IGRpZCBydW4gdGhlIHNjcmlwdCB0aGUgZmlsZQ0KICAgICAgICAjIGlzIGFscmVhZHkgdGhlcmUsIGFuZCB3YWl0aW5nIGxvbmdlciBvbmx5IGRlbGF5cyB0aGUgb3BlbiAtYSBmYWxsYmFjay4NCiAgICAgICAgaWYgd2FpdF9mb3Jfb3V0cHV0KG91dF9maWxlLCAzKToNCiAgICAgICAgICAgIHJldHVybiAiYXBwbGUtZXZlbnRzIg0KICAgICAgICBlcnJvcnMuYXBwZW5kKCJvc2FzY3JpcHQ6ICVzIiAlIChkb25lLnN0ZGVyciBvciBkb25lLnN0ZG91dCBvciAibm8gb3V0cHV0IGZpbGUiKS5zdHJpcCgpKQ0KICAgIGV4Y2VwdCBzdWJwcm9jZXNzLlRpbWVvdXRFeHBpcmVkOg0KICAgICAgICBlcnJvcnMuYXBwZW5kKCJvc2FzY3JpcHQ6IHRpbWVvdXQgYWZ0ZXIgJXNzIiAlIHRpbWVvdXQpDQogICAgZXhjZXB0IE9TRXJyb3IgYXMgZXJyb3I6DQogICAgICAgIGVycm9ycy5hcHBlbmQoIm9zYXNjcmlwdDogJXMiICUgZXJyb3IpDQoNCiAgICAjIEZhbGxiYWNrOiBoYW5kIHRoZSAuanN4IHRvIFBob3Rvc2hvcC4gTmVlZHMgbm8gQXV0b21hdGlvbiBwZXJtaXNzaW9uIGJ1dA0KICAgICMgaXMgYXN5bmNocm9ub3VzLCBzbyB0aGUgb3V0cHV0IGZpbGUgaGFzIHRvIGJlIHBvbGxlZCBmb3IuDQogICAgdHJ5Og0KICAgICAgICBzdWJwcm9jZXNzLnJ1bihbIm9wZW4iLCAiLWEiLCBzdHIoYXBwX3BhdGgpLCBzdHIoc2NyaXB0KV0sIGNhcHR1cmVfb3V0cHV0PVRydWUsIHRleHQ9VHJ1ZSwgdGltZW91dD0zMCkNCiAgICBleGNlcHQgKHN1YnByb2Nlc3MuVGltZW91dEV4cGlyZWQsIE9TRXJyb3IpIGFzIGVycm9yOg0KICAgICAgICBlcnJvcnMuYXBwZW5kKCJvcGVuIC1hOiAlcyIgJSBlcnJvcikNCiAgICAjIG9wZW4gLWEgcmV0dXJucyBhcyBzb29uIGFzIFBob3Rvc2hvcCBoYXMgYmVlbiBoYW5kZWQgdGhlIHNjcmlwdCwgc28gdGhpcw0KICAgICMgaGFzIHRvIHdhaXQgZm9yIGEgY29tcGxldGUgZmlsZSwgbm90IG1lcmVseSBmb3Igb25lIHRvIGFwcGVhci4NCiAgICBpZiB3YWl0X2Zvcl9vdXRwdXQob3V0X2ZpbGUsIHRpbWVvdXQpOg0KICAgICAgICByZXR1cm4gIm9wZW4tYSINCiAgICBlcnJvcnMuYXBwZW5kKCJvcGVuIC1hOiBubyBjb21wbGV0ZSBvdXRwdXQgZmlsZSB3aXRoaW4gJXNzIiAlIHRpbWVvdXQpDQoNCiAgICByYWlzZSBEaWN1dEVycm9yKA0KICAgICAgICAiUGhvdG9zaG9wIOC5hOC4oeC5iOC4leC4reC4muC4quC4meC4reC4hyDigJQgIiArICIgfCAiLmpvaW4oZXJyb3JzKQ0KICAgICAgICArICIgfCDguJbguYnguLLguILguLbguYnguJkgTm90IGF1dGhvcml6ZWQg4LmD4Lir4LmJ4LmA4Lib4Li04LiUIFN5c3RlbSBTZXR0aW5ncyA+IFByaXZhY3kgJiBTZWN1cml0eSA+IEF1dG9tYXRpb24iDQogICAgKQ0KDQoNCmRlZiBkaWN1dF9ieXRlcyhwYXlsb2FkLCBtaW1lLCB0aW1lb3V0LCBrZWVwX3dvcmssIHRyaW09VHJ1ZSk6DQogICAgIiIiUmVtb3ZlIHRoZSBiYWNrZ3JvdW5kIGZyb20gaW1hZ2UgYnl0ZXMgYW5kIHJldHVybiB0cmFuc3BhcmVudCBQTkcgYnl0ZXMuIiIiDQogICAgc3RhdHVzID0gcGhvdG9zaG9wX3N0YXR1cygpDQogICAgaWYgbm90IHN0YXR1c1siZm91bmQiXToNCiAgICAgICAgcmFpc2UgRGljdXRFcnJvcigi4LmE4Lih4LmI4Lie4LiaIEFkb2JlIFBob3Rvc2hvcCDguJrguJnguYDguITguKPguLfguYjguK3guIfguJnguLXguYkgKOC4leC5ieC4reC4h+C5gOC4m+C5h+C4mSAyMDIyIOC4guC4tuC5ieC4meC5hOC4mykiKQ0KDQogICAgc3VmZml4ID0gRVhURU5TSU9OX0JZX01JTUUuZ2V0KChtaW1lIG9yICIiKS5sb3dlcigpLCAiLnBuZyIpDQogICAgd29yayA9IFBhdGgodGVtcGZpbGUuZ2V0dGVtcGRpcigpKSAvICJkaWN1dC1icmlkZ2UiIC8gdXVpZC51dWlkNCgpLmhleA0KICAgIHdvcmsubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQ0KICAgIHNyYyA9IHdvcmsgLyAoInNvdXJjZSIgKyBzdWZmaXgpDQogICAgb3V0ID0gd29yayAvICJzb3VyY2VfZGljdXQucG5nIg0KICAgIHNjcmlwdCA9IHdvcmsgLyAicnVuLmpzeCINCiAgICBzcmMud3JpdGVfYnl0ZXMocGF5bG9hZCkNCiAgICBzY3JpcHQud3JpdGVfdGV4dCgNCiAgICAgICAgSlNYX1RFTVBMQVRFICUgeyJzcmMiOiBqc3hfcGF0aChzcmMpLCAib3V0IjoganN4X3BhdGgob3V0KSwgInRyaW0iOiBUUklNX0xJTkUgaWYgdHJpbSBlbHNlICIifSwNCiAgICAgICAgZW5jb2Rpbmc9InV0Zi04IiwNCiAgICApDQoNCiAgICBzdGFydGVkID0gdGltZS50aW1lKCkNCiAgICB0cnk6DQogICAgICAgIHdpdGggUEhPVE9TSE9QX0xPQ0s6DQogICAgICAgICAgICBpZiBJU19XSU5ET1dTOg0KICAgICAgICAgICAgICAgIG1ldGhvZCA9IHJ1bl9waG90b3Nob3Bfd2luZG93cyhzY3JpcHQsIG91dCwgdGltZW91dCkNCiAgICAgICAgICAgIGVsaWYgSVNfTUFDOg0KICAgICAgICAgICAgICAgIG1ldGhvZCA9IHJ1bl9waG90b3Nob3BfbWFjKHNjcmlwdCwgb3V0LCB0aW1lb3V0LCBmaW5kX3Bob3Rvc2hvcF9tYWMoKSkNCiAgICAgICAgICAgIGVsc2U6DQogICAgICAgICAgICAgICAgcmFpc2UgRGljdXRFcnJvcigi4Lij4Lit4LiH4Lij4Lix4Lia4LmA4LiJ4Lie4Liy4LiwIFdpbmRvd3Mg4LmB4Lil4LiwIG1hY09TIikNCiAgICAgICAgcmVzdWx0ID0gb3V0LnJlYWRfYnl0ZXMoKQ0KICAgICAgICBpZiBub3QgcmVzdWx0Og0KICAgICAgICAgICAgcmFpc2UgRGljdXRFcnJvcigiUGhvdG9zaG9wIOC4hOC4t+C4meC5hOC4n+C4peC5jOC4p+C5iOC4suC4hyIpDQogICAgICAgIHJldHVybiB7DQogICAgICAgICAgICAicG5nIjogcmVzdWx0LA0KICAgICAgICAgICAgIm1ldGhvZCI6IG1ldGhvZCwNCiAgICAgICAgICAgICJtcyI6IGludCgodGltZS50aW1lKCkgLSBzdGFydGVkKSAqIDEwMDApLA0KICAgICAgICAgICAgInBob3Rvc2hvcCI6IHN0YXR1c1sibmFtZSJdLA0KICAgICAgICB9DQogICAgZmluYWxseToNCiAgICAgICAgaWYgbm90IGtlZXBfd29yazoNCiAgICAgICAgICAgIHNodXRpbC5ybXRyZWUod29yaywgaWdub3JlX2Vycm9ycz1UcnVlKQ0KDQoNCmRlZiBkZWNvZGVfcmVxdWVzdF9pbWFnZShib2R5KToNCiAgICBkYXRhX3VybCA9IGJvZHkuZ2V0KCJkYXRhVXJsIikgb3IgIiINCiAgICBpZiBkYXRhX3VybDoNCiAgICAgICAgbWF0Y2ggPSBEQVRBX1VSTF9SRS5tYXRjaChkYXRhX3VybC5zdHJpcCgpKQ0KICAgICAgICBpZiBub3QgbWF0Y2g6DQogICAgICAgICAgICByYWlzZSBEaWN1dEVycm9yKCJkYXRhVXJsIOC5hOC4oeC5iOC4luC4ueC4geC4leC5ieC4reC4hyAo4LiV4LmJ4Lit4LiH4LmA4Lib4LmH4LiZIGJhc2U2NCBkYXRhIFVSTCkiKQ0KICAgICAgICByZXR1cm4gYmFzZTY0LmI2NGRlY29kZShtYXRjaC5ncm91cCgicGF5bG9hZCIpKSwgbWF0Y2guZ3JvdXAoIm1pbWUiKSBvciAiaW1hZ2UvcG5nIg0KICAgIHJhdyA9IGJvZHkuZ2V0KCJiYXNlNjQiKSBvciAiIg0KICAgIGlmIHJhdzoNCiAgICAgICAgcmV0dXJuIGJhc2U2NC5iNjRkZWNvZGUocmF3KSwgYm9keS5nZXQoIm1pbWUiKSBvciAiaW1hZ2UvcG5nIg0KICAgIHJhaXNlIERpY3V0RXJyb3IoIuC5hOC4oeC5iOC4oeC4teC4guC5ieC4reC4oeC4ueC4peC4o+C4ueC4m+C5g+C4mSByZXF1ZXN0IikNCg0KDQojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQojIEhUVFAgbGF5ZXINCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCg0KY2xhc3MgQnJpZGdlSGFuZGxlcihCYXNlSFRUUFJlcXVlc3RIYW5kbGVyKToNCiAgICBzZXJ2ZXJfdmVyc2lvbiA9ICJEaWN1dFBTQnJpZGdlLyIgKyBWRVJTSU9ODQogICAgcHJvdG9jb2xfdmVyc2lvbiA9ICJIVFRQLzEuMSINCiAgICB0aW1lb3V0X3NlY29uZHMgPSBERUZBVUxUX1RJTUVPVVQNCiAgICBrZWVwX3dvcmsgPSBGYWxzZQ0KDQogICAgZGVmIGxvZ19tZXNzYWdlKHNlbGYsIGZtdCwgKmFyZ3MpOg0KICAgICAgICBlbWl0KGZtdCAlIGFyZ3MpDQoNCiAgICAjIC0tIGhlbHBlcnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQogICAgZGVmIGNvcnNfaGVhZGVycyhzZWxmLCBvcmlnaW4pOg0KICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJBY2Nlc3MtQ29udHJvbC1BbGxvdy1PcmlnaW4iLCBvcmlnaW4gb3IgIioiKQ0KICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJWYXJ5IiwgIk9yaWdpbiIpDQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LU1ldGhvZHMiLCAiR0VULCBQT1NULCBPUFRJT05TIikNCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyIsICJDb250ZW50LVR5cGUiKQ0KICAgICAgICAjIENocm9tZSdzIFByaXZhdGUgTmV0d29yayBBY2Nlc3MgcHJlZmxpZ2h0IGZvciBodHRwcyAtPiAxMjcuMC4wLjEuDQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LVByaXZhdGUtTmV0d29yayIsICJ0cnVlIikNCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtTWF4LUFnZSIsICI2MDAiKQ0KDQogICAgZGVmIHJlcGx5KHNlbGYsIHN0YXR1cywgcGF5bG9hZCk6DQogICAgICAgIG9yaWdpbiA9IHNlbGYuaGVhZGVycy5nZXQoIk9yaWdpbiIpDQogICAgICAgIGJvZHkgPSBqc29uLmR1bXBzKHBheWxvYWQsIGVuc3VyZV9hc2NpaT1GYWxzZSkuZW5jb2RlKCJ1dGYtOCIpDQogICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZShzdGF0dXMpDQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkNvbnRlbnQtVHlwZSIsICJhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04IikNCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1MZW5ndGgiLCBzdHIobGVuKGJvZHkpKSkNCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ2FjaGUtQ29udHJvbCIsICJuby1zdG9yZSIpDQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIlgtQ29udGVudC1UeXBlLU9wdGlvbnMiLCAibm9zbmlmZiIpDQogICAgICAgIHNlbGYuY29yc19oZWFkZXJzKG9yaWdpbikNCiAgICAgICAgc2VsZi5lbmRfaGVhZGVycygpDQogICAgICAgIHNlbGYud2ZpbGUud3JpdGUoYm9keSkNCg0KICAgIGRlZiBndWFyZF9vcmlnaW4oc2VsZik6DQogICAgICAgIG9yaWdpbiA9IHNlbGYuaGVhZGVycy5nZXQoIk9yaWdpbiIpDQogICAgICAgIGlmIG9yaWdpbl9hbGxvd2VkKG9yaWdpbik6DQogICAgICAgICAgICByZXR1cm4gVHJ1ZQ0KICAgICAgICBzZWxmLnJlcGx5KDQwMywgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAib3JpZ2luIOC5hOC4oeC5iOC5hOC4lOC5ieC4o+C4seC4muC4reC4meC4uOC4jeC4suC4lTogJXMiICUgb3JpZ2lufSkNCiAgICAgICAgcmV0dXJuIEZhbHNlDQoNCiAgICAjIC0tIHJvdXRlcyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQogICAgZGVmIGRvX09QVElPTlMoc2VsZik6ICAjIG5vcWE6IE44MDIgLSBCYXNlSFRUUFJlcXVlc3RIYW5kbGVyIG5hbWluZw0KICAgICAgICBvcmlnaW4gPSBzZWxmLmhlYWRlcnMuZ2V0KCJPcmlnaW4iKQ0KICAgICAgICBpZiBub3Qgb3JpZ2luX2FsbG93ZWQob3JpZ2luKToNCiAgICAgICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZSg0MDMpDQogICAgICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LUxlbmd0aCIsICIwIikNCiAgICAgICAgICAgIHNlbGYuZW5kX2hlYWRlcnMoKQ0KICAgICAgICAgICAgcmV0dXJuDQogICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZSgyMDQpDQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkNvbnRlbnQtTGVuZ3RoIiwgIjAiKQ0KICAgICAgICBzZWxmLmNvcnNfaGVhZGVycyhvcmlnaW4pDQogICAgICAgIHNlbGYuZW5kX2hlYWRlcnMoKQ0KDQogICAgZGVmIGRvX0dFVChzZWxmKTogICMgbm9xYTogTjgwMg0KICAgICAgICBpZiBzZWxmLnBhdGguc3BsaXQoIj8iKVswXSBub3QgaW4gKCIvaGVhbHRoIiwgIi8iKToNCiAgICAgICAgICAgIHNlbGYucmVwbHkoNDA0LCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJub3QgZm91bmQifSkNCiAgICAgICAgICAgIHJldHVybg0KICAgICAgICBpZiBub3Qgc2VsZi5ndWFyZF9vcmlnaW4oKToNCiAgICAgICAgICAgIHJldHVybg0KICAgICAgICBzdGF0dXMgPSBwaG90b3Nob3Bfc3RhdHVzKCkNCiAgICAgICAgc2VsZi5yZXBseSgyMDAsIHsNCiAgICAgICAgICAgICJvayI6IFRydWUsDQogICAgICAgICAgICAibmFtZSI6ICJkaWN1dC1wcy1icmlkZ2UiLA0KICAgICAgICAgICAgInZlcnNpb24iOiBWRVJTSU9OLA0KICAgICAgICAgICAgInBsYXRmb3JtIjogc3lzLnBsYXRmb3JtLA0KICAgICAgICAgICAgIm9zIjogcGxhdGZvcm0ucGxhdGZvcm0oKSwNCiAgICAgICAgICAgICJwaG90b3Nob3AiOiBzdGF0dXNbIm5hbWUiXSwNCiAgICAgICAgICAgICJwaG90b3Nob3BGb3VuZCI6IHN0YXR1c1siZm91bmQiXSwNCiAgICAgICAgICAgICJidXN5IjogUEhPVE9TSE9QX0xPQ0subG9ja2VkKCksDQogICAgICAgIH0pDQoNCiAgICBkZWYgZG9fUE9TVChzZWxmKTogICMgbm9xYTogTjgwMg0KICAgICAgICBpZiBzZWxmLnBhdGguc3BsaXQoIj8iKVswXSAhPSAiL2RpY3V0IjoNCiAgICAgICAgICAgIHNlbGYucmVwbHkoNDA0LCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJub3QgZm91bmQifSkNCiAgICAgICAgICAgIHJldHVybg0KICAgICAgICBpZiBub3Qgc2VsZi5ndWFyZF9vcmlnaW4oKToNCiAgICAgICAgICAgIHJldHVybg0KICAgICAgICB0cnk6DQogICAgICAgICAgICBsZW5ndGggPSBpbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiKSBvciAwKQ0KICAgICAgICBleGNlcHQgVmFsdWVFcnJvcjoNCiAgICAgICAgICAgIGxlbmd0aCA9IDANCiAgICAgICAgaWYgbGVuZ3RoIDw9IDA6DQogICAgICAgICAgICBzZWxmLnJlcGx5KDQwMCwgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAicmVxdWVzdCDguKfguYjguLLguIcifSkNCiAgICAgICAgICAgIHJldHVybg0KICAgICAgICBpZiBsZW5ndGggPiBNQVhfQk9EWV9CWVRFUzoNCiAgICAgICAgICAgIHNlbGYucmVwbHkoNDEzLCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICLguKPguLnguJvguYPguKvguI3guYjguYDguIHguLTguJkgJWQgTUIiICUgKE1BWF9CT0RZX0JZVEVTIC8vIDEwMjQgLy8gMTAyNCl9KQ0KICAgICAgICAgICAgcmV0dXJuDQogICAgICAgIHRyeToNCiAgICAgICAgICAgIGJvZHkgPSBqc29uLmxvYWRzKHNlbGYucmZpbGUucmVhZChsZW5ndGgpLmRlY29kZSgidXRmLTgiKSkNCiAgICAgICAgZXhjZXB0IChWYWx1ZUVycm9yLCBVbmljb2RlRGVjb2RlRXJyb3IpIGFzIGVycm9yOg0KICAgICAgICAgICAgc2VsZi5yZXBseSg0MDAsIHsib2siOiBGYWxzZSwgImVycm9yIjogIuC4reC5iOC4suC4mSBKU09OIOC5hOC4oeC5iOC5hOC4lOC5iTogJXMiICUgZXJyb3J9KQ0KICAgICAgICAgICAgcmV0dXJuDQoNCiAgICAgICAgbmFtZSA9IHN0cihib2R5LmdldCgibmFtZSIpIG9yICJpbWFnZSIpDQogICAgICAgIHRyaW0gPSBib2R5LmdldCgidHJpbSIpIGlzIG5vdCBGYWxzZQ0KICAgICAgICB0cnk6DQogICAgICAgICAgICBwYXlsb2FkLCBtaW1lID0gZGVjb2RlX3JlcXVlc3RfaW1hZ2UoYm9keSkNCiAgICAgICAgICAgIHJlc3VsdCA9IGRpY3V0X2J5dGVzKHBheWxvYWQsIG1pbWUsIHNlbGYudGltZW91dF9zZWNvbmRzLCBzZWxmLmtlZXBfd29yaywgdHJpbSkNCiAgICAgICAgZXhjZXB0IERpY3V0RXJyb3IgYXMgZXJyb3I6DQogICAgICAgICAgICBzZWxmLmxvZ19tZXNzYWdlKCJkaWN1dCBGQUlMRUQgJXMgLSAlcyIsIG5hbWUsIGVycm9yKQ0KICAgICAgICAgICAgc2VsZi5yZXBseSg1MDIsIHsib2siOiBGYWxzZSwgImVycm9yIjogc3RyKGVycm9yKX0pDQogICAgICAgICAgICByZXR1cm4NCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlcnJvcjogICMgbm9xYTogQkxFMDAxIC0gc3VyZmFjZSB0aGUgcmVhbCBjYXVzZQ0KICAgICAgICAgICAgc2VsZi5sb2dfbWVzc2FnZSgiZGljdXQgRVJST1IgJXMgLSAlcyIsIG5hbWUsIGVycm9yKQ0KICAgICAgICAgICAgc2VsZi5yZXBseSg1MDAsIHsib2siOiBGYWxzZSwgImVycm9yIjogIiVzOiAlcyIgJSAodHlwZShlcnJvcikuX19uYW1lX18sIGVycm9yKX0pDQogICAgICAgICAgICByZXR1cm4NCg0KICAgICAgICBzZWxmLmxvZ19tZXNzYWdlKCJkaWN1dCBvayAlcyAoJXMsICVzbXMpIiwgbmFtZSwgcmVzdWx0WyJtZXRob2QiXSwgcmVzdWx0WyJtcyJdKQ0KICAgICAgICBzZWxmLnJlcGx5KDIwMCwgew0KICAgICAgICAgICAgIm9rIjogVHJ1ZSwNCiAgICAgICAgICAgICJuYW1lIjogbmFtZSwNCiAgICAgICAgICAgICJtZXRob2QiOiByZXN1bHRbIm1ldGhvZCJdLA0KICAgICAgICAgICAgIm1zIjogcmVzdWx0WyJtcyJdLA0KICAgICAgICAgICAgInBob3Rvc2hvcCI6IHJlc3VsdFsicGhvdG9zaG9wIl0sDQogICAgICAgICAgICAidHJpbW1lZCI6IHRyaW0sDQogICAgICAgICAgICAiYnl0ZXMiOiBsZW4ocmVzdWx0WyJwbmciXSksDQogICAgICAgICAgICAiZGF0YVVybCI6ICJkYXRhOmltYWdlL3BuZztiYXNlNjQsIiArIGJhc2U2NC5iNjRlbmNvZGUocmVzdWx0WyJwbmciXSkuZGVjb2RlKCJhc2NpaSIpLA0KICAgICAgICB9KQ0KDQoNCmRlZiBzZWxmdGVzdChpbWFnZV9wYXRoLCB0aW1lb3V0LCBrZWVwX3dvcmspOg0KICAgIHNvdXJjZSA9IFBhdGgoaW1hZ2VfcGF0aCkNCiAgICBpZiBub3Qgc291cmNlLmlzX2ZpbGUoKToNCiAgICAgICAgZW1pdCgi4LmE4Lih4LmI4Lie4Lia4LmE4Lif4Lil4LmMOiAlcyIgJSBzb3VyY2UpDQogICAgICAgIHJldHVybiAxDQogICAgc3RhdHVzID0gcGhvdG9zaG9wX3N0YXR1cygpDQogICAgZW1pdCgicGxhdGZvcm0gIDogJXMiICUgc3lzLnBsYXRmb3JtKQ0KICAgIGVtaXQoInBob3Rvc2hvcCA6ICVzIiAlIChzdGF0dXNbIm5hbWUiXSBvciAiTk9UIEZPVU5EIikpDQogICAgaWYgbm90IHN0YXR1c1siZm91bmQiXToNCiAgICAgICAgcmV0dXJuIDENCiAgICBtaW1lID0gewogICAgICAgICIucG5nIjogImltYWdlL3BuZyIsICIud2VicCI6ICJpbWFnZS93ZWJwIiwgIi50aWYiOiAiaW1hZ2UvdGlmZiIsCiAgICAgICAgIi50aWZmIjogImltYWdlL3RpZmYiLCAiLmJtcCI6ICJpbWFnZS9ibXAiLAogICAgfS5nZXQoc291cmNlLnN1ZmZpeC5sb3dlcigpLCAiaW1hZ2UvanBlZyIpCiAgICB0cnk6DQogICAgICAgIHJlc3VsdCA9IGRpY3V0X2J5dGVzKHNvdXJjZS5yZWFkX2J5dGVzKCksIG1pbWUsIHRpbWVvdXQsIGtlZXBfd29yaykNCiAgICBleGNlcHQgRGljdXRFcnJvciBhcyBlcnJvcjoNCiAgICAgICAgZW1pdCgiRkFJTEVEOiAlcyIgJSBlcnJvcikNCiAgICAgICAgcmV0dXJuIDENCiAgICBvdXQgPSBzb3VyY2Uud2l0aF9uYW1lKHNvdXJjZS5zdGVtICsgIl9kaWN1dC5wbmciKQ0KICAgIG91dC53cml0ZV9ieXRlcyhyZXN1bHRbInBuZyJdKQ0KICAgIGVtaXQoIk9LICglcywgJXNtcykgLT4gJXMiICUgKHJlc3VsdFsibWV0aG9kIl0sIHJlc3VsdFsibXMiXSwgb3V0KSkNCiAgICByZXR1cm4gMA0KDQoNCmRlZiBtYWluKCk6DQogICAgcGFyc2VyID0gYXJncGFyc2UuQXJndW1lbnRQYXJzZXIoZGVzY3JpcHRpb249IkRpY3V0IFBTIEJyaWRnZSIpDQogICAgcGFyc2VyLmFkZF9hcmd1bWVudCgiLS1ob3N0IiwgZGVmYXVsdD1ERUZBVUxUX0hPU1QpDQogICAgcGFyc2VyLmFkZF9hcmd1bWVudCgiLS1wb3J0IiwgdHlwZT1pbnQsIGRlZmF1bHQ9aW50KG9zLmVudmlyb24uZ2V0KCJESUNVVF9CUklER0VfUE9SVCIsIERFRkFVTFRfUE9SVCkpKQ0KICAgIHBhcnNlci5hZGRfYXJndW1lbnQoIi0tdGltZW91dCIsIHR5cGU9aW50LCBkZWZhdWx0PURFRkFVTFRfVElNRU9VVCkNCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50KCItLWtlZXAtd29yayIsIGFjdGlvbj0ic3RvcmVfdHJ1ZSIsIGhlbHA9ImtlZXAgdGhlIHRlbXAgZm9sZGVyIGZvciBkZWJ1Z2dpbmciKQ0KICAgIHBhcnNlci5hZGRfYXJndW1lbnQoIi0tc2VsZnRlc3QiLCBtZXRhdmFyPSJJTUFHRSIsIGhlbHA9ImN1dCBvbmUgZmlsZSBhbmQgZXhpdCIpDQogICAgYXJncyA9IHBhcnNlci5wYXJzZV9hcmdzKCkNCg0KICAgIGxvYWRfZXh0cmFfb3JpZ2lucygpDQogICAgaWYgYXJncy5zZWxmdGVzdDoNCiAgICAgICAgcmFpc2UgU3lzdGVtRXhpdChzZWxmdGVzdChhcmdzLnNlbGZ0ZXN0LCBhcmdzLnRpbWVvdXQsIGFyZ3Mua2VlcF93b3JrKSkNCg0KICAgIEJyaWRnZUhhbmRsZXIudGltZW91dF9zZWNvbmRzID0gYXJncy50aW1lb3V0DQogICAgQnJpZGdlSGFuZGxlci5rZWVwX3dvcmsgPSBhcmdzLmtlZXBfd29yaw0KICAgIHNlcnZlciA9IFRocmVhZGluZ0hUVFBTZXJ2ZXIoKGFyZ3MuaG9zdCwgYXJncy5wb3J0KSwgQnJpZGdlSGFuZGxlcikNCiAgICBzdGF0dXMgPSBwaG90b3Nob3Bfc3RhdHVzKCkNCiAgICBlbWl0KCJEaWN1dCBQUyBCcmlkZ2UgJXMiICUgVkVSU0lPTikNCiAgICBlbWl0KCJsaXN0ZW5pbmcgOiBodHRwOi8vJXM6JWQiICUgKGFyZ3MuaG9zdCwgYXJncy5wb3J0KSkNCiAgICBlbWl0KCJwaG90b3Nob3AgOiAlcyIgJSAoc3RhdHVzWyJuYW1lIl0gb3IgIk5PVCBGT1VORCAtIOC4leC4tOC4lOC4leC4seC5ieC4hyBQaG90b3Nob3AgMjAyMisg4LiB4LmI4Lit4LiZIikpDQogICAgZW1pdCgic3RvcCAgICAgIDogQ3RybCtDIikNCiAgICB0cnk6DQogICAgICAgIHNlcnZlci5zZXJ2ZV9mb3JldmVyKCkNCiAgICBleGNlcHQgS2V5Ym9hcmRJbnRlcnJ1cHQ6DQogICAgICAgIGVtaXQoInN0b3BwZWQiKQ0KICAgIGZpbmFsbHk6DQogICAgICAgIHNlcnZlci5zZXJ2ZXJfY2xvc2UoKQ0KDQoNCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6DQogICAgbWFpbigpDQo=';
  /* BRIDGE_SOURCE_B64_END */

  var probeCache = null;
  var probeInFlight = null;

  // ---------------------------------------------------------------- helpers
  function isMac() {
    return /mac|iphone|ipad/i.test(navigator.platform || navigator.userAgent || '');
  }

  function fetchWithTimeout(url, options, timeoutMs) {
    var controller = new AbortController();
    var timer = setTimeout(function () { controller.abort(); }, timeoutMs);
    var settings = Object.assign({}, options, { signal: controller.signal });
    if (options && options.signal) {
      if (options.signal.aborted) controller.abort();
      else options.signal.addEventListener('abort', function () { controller.abort(); }, { once: true });
    }
    return fetch(url, settings).finally(function () { clearTimeout(timer); });
  }

  function blobToDataUrl(blob) {
    return new Promise(function (resolve, reject) {
      var reader = new FileReader();
      reader.onload = function () { resolve(String(reader.result)); };
      reader.onerror = function () { reject(new Error('อ่านไฟล์รูปไม่สำเร็จ')); };
      reader.readAsDataURL(blob);
    });
  }

  function dataUrlToBlob(dataUrl) {
    var comma = dataUrl.indexOf(',');
    var head = dataUrl.slice(0, comma);
    var mime = (head.match(/data:([^;]+)/) || [])[1] || 'image/png';
    var binary = atob(dataUrl.slice(comma + 1));
    var bytes = new Uint8Array(binary.length);
    for (var i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
    return new Blob([bytes], { type: mime });
  }

  function canvasToDataUrl(canvas) {
    return canvas.toDataURL('image/png');
  }

  // Images that came from another origin have to go through a canvas anyway,
  // so a single normaliser covers every consumer discovered from the Registry.
  function toDataUrl(source) {
    if (!source) return Promise.reject(new Error('ไม่มีรูปให้ไดคัท'));
    if (typeof source === 'string') {
      if (source.indexOf('data:') === 0) return Promise.resolve(source);
      return fetch(source).then(function (response) {
        if (!response.ok) throw new Error('โหลดรูปไม่สำเร็จ (' + response.status + ')');
        return response.blob();
      }).then(blobToDataUrl);
    }
    if (typeof HTMLCanvasElement !== 'undefined' && source instanceof HTMLCanvasElement) {
      return Promise.resolve(canvasToDataUrl(source));
    }
    if (typeof HTMLImageElement !== 'undefined' && source instanceof HTMLImageElement) {
      var canvas = document.createElement('canvas');
      canvas.width = source.naturalWidth || source.width;
      canvas.height = source.naturalHeight || source.height;
      canvas.getContext('2d').drawImage(source, 0, 0);
      return Promise.resolve(canvasToDataUrl(canvas));
    }
    if (typeof Blob !== 'undefined' && source instanceof Blob) return blobToDataUrl(source);
    return Promise.reject(new Error('รูปแบบรูปไม่รองรับ'));
  }

  // Plain numeric compare: the bridge only ever reports x.y.z.
  function olderThanRequired(version) {
    var have = String(version || '').split('.').map(Number);
    var need = REQUIRED_BRIDGE.split('.').map(Number);
    for (var i = 0; i < need.length; i += 1) {
      var a = have[i] || 0;
      if (a !== need[i]) return a < need[i];
    }
    return false;
  }

  // ----------------------------------------------------------------- probe
  function probe(options) {
    var force = options && options.force;
    var now = Date.now();
    if (!force && probeCache && now < probeCache.expires) return Promise.resolve(probeCache.value);
    if (!force && probeInFlight) return probeInFlight;

    probeInFlight = fetchWithTimeout(ENDPOINT + '/health', { cache: 'no-store' }, PROBE_TIMEOUT_MS)
      .then(function (response) {
        if (!response.ok) throw new Error('bridge ตอบ ' + response.status);
        return response.json();
      })
      .then(function (data) {
        var stale = olderThanRequired(data.version || '');
        return {
          available: true,
          photoshopFound: !!data.photoshopFound,
          photoshop: data.photoshop || '',
          version: data.version || '',
          platform: data.platform || '',
          busy: !!data.busy,
          stale: stale,
          error: !data.photoshopFound
            ? 'ไม่พบ Adobe Photoshop บนเครื่องนี้ (ต้องเป็น 2022 ขึ้นไป)'
            : stale
              ? 'Dicut PS Bridge บนเครื่องนี้เป็นรุ่นเก่า (' + (data.version || 'ไม่ทราบรุ่น') + ') ต้องอัปเดตเป็น ' + REQUIRED_BRIDGE
              : ''
        };
      })
      .catch(function (error) {
        return {
          available: false,
          photoshopFound: false,
          photoshop: '',
          version: '',
          platform: '',
          busy: false,
          stale: false,
          error: error && error.name === 'AbortError'
            ? 'ต่อ Dicut PS Bridge ไม่ทัน (timeout)'
            : 'ยังไม่ได้เปิด Dicut PS Bridge บนเครื่องนี้'
        };
      })
      .then(function (value) {
        probeCache = { value: value, expires: Date.now() + (value.available ? PROBE_TTL_OK_MS : PROBE_TTL_FAIL_MS) };
        probeInFlight = null;
        return value;
      });
    return probeInFlight;
  }

  // ------------------------------------------------------------------- cut
  function cut(source, name, options) {
    var settings = options || {};
    return toDataUrl(source).then(function (dataUrl) {
      return fetchWithTimeout(ENDPOINT + '/dicut', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        // trim:false keeps the cut on the original canvas, which is what a
        // caller needs to show an aligned before/after comparison.
        body: JSON.stringify({ name: name || 'image', dataUrl: dataUrl, trim: settings.trim !== false }),
        signal: settings.signal
      }, settings.timeoutMs || CUT_TIMEOUT_MS);
    }).then(function (response) {
      return response.json().catch(function () { return {}; }).then(function (data) {
        if (!response.ok || !data.ok) {
          throw new Error(data.error || ('Dicut PS ไม่สำเร็จ (' + response.status + ')'));
        }
        return {
          dataUrl: data.dataUrl,
          blob: dataUrlToBlob(data.dataUrl),
          bytes: data.bytes || 0,
          ms: data.ms || 0,
          method: data.method || '',
          photoshop: data.photoshop || ''
        };
      });
    }).catch(function (error) {
      probeCache = null;  // a failure may mean the bridge died: re-probe next time
      if (error && error.name === 'AbortError') throw new Error('ยกเลิกหรือรอ Photoshop นานเกินกำหนด');
      if (error instanceof TypeError) throw new Error('ติดต่อ Dicut PS Bridge ไม่ได้ — ตรวจว่าเปิดอยู่หรือยัง');
      throw error;
    });
  }

  // Photoshop is single-instance, so the queue is deliberately sequential.
  function cutMany(items, options) {
    var settings = options || {};
    var list = Array.prototype.slice.call(items || []);
    var results = [];
    var index = 0;

    function step() {
      if (index >= list.length) return Promise.resolve(results);
      if (settings.signal && settings.signal.aborted) return Promise.resolve(results);
      var item = list[index];
      if (settings.onProgress) settings.onProgress({ index: index, total: list.length, item: item, phase: 'start' });
      return cut(item.source, item.name, { signal: settings.signal, timeoutMs: settings.timeoutMs, trim: settings.trim })
        .then(function (result) {
          results.push({ item: item, ok: true, result: result });
          if (settings.onProgress) settings.onProgress({ index: index, total: list.length, item: item, phase: 'done', result: result });
        })
        .catch(function (error) {
          results.push({ item: item, ok: false, error: error });
          if (settings.onProgress) settings.onProgress({ index: index, total: list.length, item: item, phase: 'error', error: error });
        })
        .then(function () { index += 1; return step(); });
    }
    return step();
  }

  // ------------------------------------------------------------ help modal
  var helpNodes = null;
  var helpReturnFocus = null;

  // Shipped as a real stylesheet, not an injected <style> element: the Image
  // Downloader serves a Content-Security-Policy with style-src 'self' and no
  // 'unsafe-inline', which blocks inline style elements outright.
  function injectHelpStyles() {
    if (document.getElementById('dicut-ps-style')) return;
    var link = document.createElement('link');
    link.id = 'dicut-ps-style';
    link.rel = 'stylesheet';
    link.href = SCRIPT_URL ? SCRIPT_URL.replace(/dicut-ps\.js(\?.*)?$/, 'dicut-ps.css') : 'dicut-ps.css';
    document.head.appendChild(link);
  }

  // ------------------------------------------------- one-file installers
  // Both scripts carry the whole bridge as base64 and unpack it into
  // ~/.dicut-bridge, so the only thing a first-time user handles is one file.
  function wrapBase64(width) {
    var lines = [];
    for (var i = 0; i < BRIDGE_SOURCE_B64.length; i += width) lines.push(BRIDGE_SOURCE_B64.slice(i, i + width));
    return lines;
  }

  function windowsInstaller() {
    // certutil is the only base64 decoder guaranteed to exist before Python is
    // located, and it accepts the certificate envelope reliably.
    var lines = wrapBase64(76);
    var out = [
      '@echo off',
      'title Dicut PS Bridge setup',
      'setlocal',
      'set "DIR=%USERPROFILE%\\.dicut-bridge"',
      'if not exist "%DIR%" mkdir "%DIR%"',
      'set "B64=%DIR%\\bridge.b64"',
      'echo -----BEGIN CERTIFICATE----->"%B64%"'
    ];
    for (var i = 0; i < lines.length; i += 1) out.push('echo ' + lines[i] + '>>"%B64%"');
    out = out.concat([
      'echo -----END CERTIFICATE----->>"%B64%"',
      'certutil -f -decode "%B64%" "%DIR%\\dicut_bridge.py" >nul',
      'if errorlevel 1 (echo Could not unpack the bridge. & pause & exit /b 1)',
      'del "%B64%"',
      'set "PY="',
      'for /f "delims=" %%i in (\'where pythonw.exe 2^>nul\') do if not defined PY set "PY=%%i"',
      'if not defined PY for /f "delims=" %%i in (\'where python.exe 2^>nul\') do if not defined PY set "PY=%%i"',
      'if not defined PY for /f "delims=" %%i in (\'dir /b /ad "%LOCALAPPDATA%\\Programs\\Python" 2^>nul\') do ' +
        'if not defined PY if exist "%LOCALAPPDATA%\\Programs\\Python\\%%i\\pythonw.exe" set "PY=%LOCALAPPDATA%\\Programs\\Python\\%%i\\pythonw.exe"',
      'if not defined PY (echo Python 3 was not found. Install it from python.org and run this file again. & pause & exit /b 1)',
      // An already-running bridge owns the port, so a re-run to update would
      // otherwise leave the old build serving. Single quotes only: this line
      // has to survive being written into a .bat.
      'powershell -NoProfile -Command "Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like \'*dicut_bridge.py*\' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }" >nul 2>&1',
      'set "STARTUP=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"',
      'echo @echo off>"%STARTUP%\\DicutPSBridge.cmd"',
      'echo start "" "%PY%" "%DIR%\\dicut_bridge.py">>"%STARTUP%\\DicutPSBridge.cmd"',
      'start "" "%PY%" "%DIR%\\dicut_bridge.py"',
      'echo.',
      'echo Starting the bridge...',
      // Do not claim success before the service actually answers: a bridge that
      // dies on startup used to print "installed and started" all the same.
      'set "OK="',
      'for /l %%i in (1,1,10) do (',
      '  if not defined OK (',
      '    curl -s -m 2 -o nul http://127.0.0.1:8799/health && set "OK=1"',
      '    if not defined OK ping -n 2 127.0.0.1 >nul',
      '  )',
      ')',
      'echo.',
      'if defined OK (',
      '  echo Dicut PS Bridge is running.',
      '  echo It will start again automatically every time you log in.',
      '  echo Go back to the browser and press the recheck button.',
      ') else (',
      '  echo PROBLEM: the bridge was installed but is not answering.',
      '  echo Run this line to see the reason, then send the output:',
      '  echo     "%PY:pythonw.exe=python.exe%" "%DIR%\\dicut_bridge.py"',
      '  echo A log is also written to "%DIR%\\bridge.log"',
      ')',
      'echo.',
      // "timeout" refuses to run whenever stdin is redirected, so the window
      // would close before the message could be read.
      'pause >nul'
    ]);
    return { name: 'dicut-ps-setup.bat', mime: 'application/octet-stream', text: out.join('\r\n') + '\r\n' };
  }

  function macInstaller() {
    // python3 is required by the bridge anyway, so it also decodes the payload
    // and the BSD/GNU base64 flag differences never come up.
    var out = [
      '#!/bin/bash',
      '# Dicut PS Bridge setup — unpacks and starts the bridge for this user.',
      'set -e',
      'DIR="$HOME/.dicut-bridge"',
      'LABEL="com.central.dicutps.bridge"',
      'PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"',
      'PY="$(command -v python3 || true)"',
      'if [ -z "$PY" ]; then echo "python3 not found — run: xcode-select --install"; exit 1; fi',
      'mkdir -p "$DIR" "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"',
      '"$PY" -c \'import base64,sys;open(sys.argv[1],"wb").write(base64.b64decode(sys.stdin.read()))\' "$DIR/dicut_bridge.py" <<\'DICUTB64\'',
      BRIDGE_SOURCE_B64,
      'DICUTB64',
      'launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || launchctl unload "$PLIST" 2>/dev/null || true',
      'cat > "$PLIST" <<PLISTEOF',
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
      '<plist version="1.0">',
      '<dict>',
      '    <key>Label</key><string>$LABEL</string>',
      '    <key>ProgramArguments</key><array><string>$PY</string><string>$DIR/dicut_bridge.py</string></array>',
      '    <key>RunAtLoad</key><true/>',
      '    <key>KeepAlive</key><true/>',
      '    <key>StandardOutPath</key><string>$HOME/Library/Logs/dicut-ps-bridge.log</string>',
      '    <key>StandardErrorPath</key><string>$HOME/Library/Logs/dicut-ps-bridge.log</string>',
      '</dict>',
      '</plist>',
      'PLISTEOF',
      'launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load "$PLIST"',
      'sleep 2',
      'if curl -fsS http://127.0.0.1:8799/health >/dev/null 2>&1; then',
      '  echo "Dicut PS Bridge installed and running."',
      'else',
      '  echo "Installed, but it has not answered yet — check ~/Library/Logs/dicut-ps-bridge.log"',
      'fi',
      'echo "Go back to the browser and press the recheck button."',
      'echo "The first cut asks macOS for permission to control Photoshop."'
    ];
    return { name: 'dicut-ps-setup.command', mime: 'application/octet-stream', text: out.join('\n') + '\n' };
  }

  function downloadInstaller(target) {
    if (!BRIDGE_SOURCE_B64) throw new Error('ตัวติดตั้งยังไม่ถูกฝังไว้ในไฟล์นี้');
    var file = target === 'mac' ? macInstaller() : windowsInstaller();
    var url = URL.createObjectURL(new Blob([file.text], { type: file.mime }));
    var link = document.createElement('a');
    link.href = url;
    link.download = file.name;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setTimeout(function () { URL.revokeObjectURL(url); }, 30000);
    return file.name;
  }

  // The async clipboard rejects whenever the document is not focused, so the
  // textarea route has to stay reachable as a fallback, not only as a polyfill.
  function copyViaTextarea(text) {
    return new Promise(function (resolve, reject) {
      var area = document.createElement('textarea');
      area.value = text;
      area.style.cssText = 'position:fixed;top:0;left:0;opacity:0';
      document.body.appendChild(area);
      area.select();
      var ok = false;
      try { ok = document.execCommand('copy'); } catch (error) { ok = false; }
      document.body.removeChild(area);
      ok ? resolve() : reject(new Error('คัดลอกไม่สำเร็จ'));
    });
  }

  function copyText(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).catch(function () { return copyViaTextarea(text); });
    }
    return copyViaTextarea(text);
  }

  // Finder will not run a downloaded .command until it is executable, and a
  // downloaded .bat trips SmartScreen, so each platform also gets the exact
  // terminal line that always works.
  var RUN_COMMAND = {
    windows: '"%USERPROFILE%\\Downloads\\dicut-ps-setup.bat"',
    mac: 'bash ~/Downloads/dicut-ps-setup.command'
  };

  function platformInstructions(target) {
    var isMacTarget = target === 'mac';
    return [
      '<li>กดปุ่มนี้เพื่อโหลดตัวติดตั้ง (ไฟล์เดียว มีทุกอย่างอยู่ข้างในแล้ว)',
      '<button type="button" class="dicut-ps-step-btn is-main dicut-ps-download">⬇ ดาวน์โหลดตัวติดตั้ง</button></li>',
      isMacTarget
        ? '<li>เปิด Terminal วางคำสั่งนี้แล้ว Enter<code>' + RUN_COMMAND.mac + '</code>' +
          '<button type="button" class="dicut-ps-step-btn dicut-ps-copy">คัดลอกคำสั่ง</button>' +
          '<div class="dicut-ps-note">ดับเบิลคลิกไฟล์ตรง ๆ ไม่ได้ เพราะไฟล์ที่โหลดมายังไม่มีสิทธิ์รัน</div></li>'
        : '<li>ดับเบิลคลิกไฟล์ที่โหลดมาได้เลย ถ้า Windows เตือนให้กด More info &gt; Run anyway' +
          '<button type="button" class="dicut-ps-step-btn dicut-ps-copy">คัดลอกคำสั่ง (ถ้าอยากรันจาก Command Prompt)</button></li>',
      '<li>ตัวติดตั้งจะเปิด Bridge ให้ทันที และเปิดเองทุกครั้งที่เข้าเครื่อง' +
        (isMacTarget ? ' ครั้งแรก macOS จะถามสิทธิ์ควบคุม Photoshop ให้กดอนุญาต' : '') + '</li>',
      '<li>กลับมาที่หน้านี้แล้วกด “ตรวจอีกครั้ง”</li>'
    ].join('');
  }

  function trapFocus(event) {
    if (event.key !== 'Tab' || !helpNodes) return;
    var focusable = helpNodes.dialog.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])');
    var items = Array.prototype.filter.call(focusable, function (node) { return node.offsetParent !== null; });
    if (!items.length) { event.preventDefault(); return; }
    var first = items[0];
    var last = items[items.length - 1];
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  }

  function buildHelp() {
    if (helpNodes) return helpNodes;
    injectHelpStyles();
    var backdrop = document.createElement('div');
    backdrop.className = 'dicut-ps-backdrop';
    backdrop.hidden = true;
    backdrop.innerHTML =
      '<div class="dicut-ps-dialog" role="dialog" aria-modal="true" aria-labelledby="dicut-ps-title" tabindex="-1">' +
        '<h2 id="dicut-ps-title">Dicut PS ยังใช้ไม่ได้</h2>' +
        '<p class="dicut-ps-status" role="status"></p>' +
        '<p>ปุ่มนี้เรียก Photoshop บนเครื่องของคุณผ่านตัวช่วยเล็ก ๆ ชื่อ <b>Dicut PS Bridge</b> ' +
        'ต้องติดตั้งครั้งเดียวต่อเครื่อง (ใช้ได้ทั้ง Windows และ Mac) และต้องมี Photoshop 2022 ขึ้นไป</p>' +
        '<div class="dicut-ps-tabs" role="tablist">' +
          '<button class="dicut-ps-tab" type="button" role="tab" data-target="windows">Windows</button>' +
          '<button class="dicut-ps-tab" type="button" role="tab" data-target="mac">Mac</button>' +
        '</div>' +
        '<ol class="dicut-ps-steps"></ol>' +
        '<div class="dicut-ps-actions">' +
          '<button type="button" class="dicut-ps-recheck">ตรวจอีกครั้ง</button>' +
          '<button type="button" class="dicut-ps-primary dicut-ps-close">ปิด</button>' +
        '</div>' +
      '</div>';
    document.body.appendChild(backdrop);

    helpNodes = {
      backdrop: backdrop,
      dialog: backdrop.querySelector('.dicut-ps-dialog'),
      title: backdrop.querySelector('#dicut-ps-title'),
      status: backdrop.querySelector('.dicut-ps-status'),
      steps: backdrop.querySelector('.dicut-ps-steps'),
      tabs: Array.prototype.slice.call(backdrop.querySelectorAll('.dicut-ps-tab')),
      recheck: backdrop.querySelector('.dicut-ps-recheck'),
      close: backdrop.querySelector('.dicut-ps-close')
    };

    helpNodes.tabs.forEach(function (tab) {
      tab.addEventListener('click', function () { selectPlatform(tab.dataset.target); });
    });
    helpNodes.close.addEventListener('click', closeHelp);
    helpNodes.recheck.addEventListener('click', function () {
      helpNodes.recheck.disabled = true;
      helpNodes.status.textContent = 'กำลังตรวจ…';
      probe({ force: true }).then(function (state) {
        helpNodes.recheck.disabled = false;
        if (state.available && state.photoshopFound && !state.stale) {
          helpNodes.status.textContent = 'เชื่อมต่อได้แล้ว (' + (state.photoshop || 'Photoshop') + ') — ปิดหน้าต่างนี้แล้วกด Dicut PS ได้เลย';
        } else {
          helpNodes.status.textContent = state.error || 'ยังเชื่อมต่อไม่ได้';
        }
      });
    });
    backdrop.addEventListener('click', function (event) { if (event.target === backdrop) closeHelp(); });
    backdrop.addEventListener('keydown', function (event) {
      if (event.key === 'Escape') { event.preventDefault(); closeHelp(); }
      else trapFocus(event);
    });
    return helpNodes;
  }

  function selectPlatform(target) {
    helpNodes.tabs.forEach(function (tab) {
      tab.setAttribute('aria-selected', String(tab.dataset.target === target));
    });
    helpNodes.steps.innerHTML = platformInstructions(target);

    var download = helpNodes.steps.querySelector('.dicut-ps-download');
    download.addEventListener('click', function () {
      try {
        var name = downloadInstaller(target);
        helpNodes.status.textContent = 'ดาวน์โหลด ' + name + ' แล้ว — ทำขั้นตอนที่ 2 ต่อ';
      } catch (error) {
        helpNodes.status.textContent = error.message;
      }
    });

    var copy = helpNodes.steps.querySelector('.dicut-ps-copy');
    copy.addEventListener('click', function () {
      var label = copy.textContent;
      copyText(target === 'mac' ? RUN_COMMAND.mac : RUN_COMMAND.windows).then(function () {
        copy.textContent = 'คัดลอกแล้ว ✓';
        setTimeout(function () { copy.textContent = label; }, 2000);
      }).catch(function () {
        helpNodes.status.textContent = 'คัดลอกไม่สำเร็จ — เลือกข้อความในกรอบแล้วคัดลอกเอง';
      });
    });
  }

  function showHelp(message, trigger, isUpdate) {
    buildHelp();
    helpReturnFocus = trigger || document.activeElement;
    helpNodes.title.textContent = isUpdate ? 'ต้องอัปเดต Dicut PS Bridge' : 'Dicut PS ยังใช้ไม่ได้';
    helpNodes.status.textContent = message || 'ยังไม่ได้เปิด Dicut PS Bridge บนเครื่องนี้';
    selectPlatform(isMac() ? 'mac' : 'windows');
    helpNodes.backdrop.hidden = false;
    helpNodes.dialog.focus();
  }

  function closeHelp() {
    if (!helpNodes || helpNodes.backdrop.hidden) return;
    helpNodes.backdrop.hidden = true;
    if (helpReturnFocus && document.contains(helpReturnFocus)) helpReturnFocus.focus();
    helpReturnFocus = null;
  }

  // Probe first; on failure open the install dialog and report "not ready" so
  // callers never have to duplicate the error path.
  function ensureReady(trigger, options) {
    return probe(options).then(function (state) {
      if (state.available && state.photoshopFound && !state.stale) return true;
      showHelp(state.error, trigger, state.stale);
      return false;
    });
  }

  window.DicutPS = {
    VERSION: VERSION,
    ENDPOINT: ENDPOINT,
    probe: probe,
    cut: cut,
    cutMany: cutMany,
    ensureReady: ensureReady,
    showHelp: showHelp,
    closeHelp: closeHelp,
    downloadInstaller: downloadInstaller,
    toDataUrl: toDataUrl,
    dataUrlToBlob: dataUrlToBlob
  };

  // Load the stylesheet up front so the dialog is never painted unstyled.
  if (document.head) injectHelpStyles();
  else document.addEventListener('DOMContentLoaded', injectHelpStyles, { once: true });
})();
